/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-auto-import
export {}
declare global {
  const useDialog: typeof import('naive-ui')['useDialog']
  const useDialogReactiveList: typeof import('naive-ui')['useDialogReactiveList']
  const useLoadingBar: typeof import('naive-ui')['useLoadingBar']
  const useMessage: typeof import('naive-ui')['useMessage']
  const useNotification: typeof import('naive-ui')['useNotification']
  const useOsTheme: typeof import('naive-ui')['useOsTheme']
  const useThemeVars: typeof import('naive-ui')['useThemeVars']
}
